version: "3.9"

services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"
      - "9009:9009"
      - "9003:9003"
      - "8812:8812"
    volumes:
      - ./data:/var/lib/questdb
  cube:
    image: "cubejs/cube:latest"
    ports:
      - "4000:4000"
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_WEB_SOCKETS=true
    volumes:
      - ./cube:/cube/conf